[package]
name = "onedrive-fuse"
version = "0.0.0"
authors = ["oxalica <oxalicc@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
env_logger = "0.7.1"
fuse = "0.3.1"
libc = "0.2.69"
log = "0.4.8"
onedrive-api = "0.6.0"
pico-args = "0.3.1"
serde = { verion = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
tokio = { version = "0.2.19", features = ["macros"] }
