[package]
name = "onedrive-fuse"
version = "0.1.0"
authors = ["oxalica <oxalicc@pm.me>"]
edition = "2018"
repository = "https://github.com/oxalica/onedrive-fuse"
keywords = ["onedrive", "fuse"]
description = "Mount OneDrive storage as FUSE filesystem"
readme = "README.md"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
bytes = "0.5.4"
config = { version = "0.10.1", default-features = false, features = ["toml"] }
env_logger = "0.7.1"
fuse = "0.3.1"
http = "0.2.1"
libc = "0.2.69"
log = "0.4.8"
nix = "0.17.0"
onedrive-api = "0.6.1"
reqwest = "0.10.4"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
sharded-slab = "0.0.9"
static_assertions = "1.1.0"
structopt = "0.3.20"
thiserror = "1.0.16"
# For `fuse` compatibility
time = "0.1"
tokio = { version = "0.2.19", features = ["macros", "sync", "rt-core"] }
