[statfs]
cache_ttl = 30

[inode]
# Cache timeout for inode metadata.
attr_cache_ttl = 30
# Size of LRU cache of inode metadata which are not referenced.
dead_lru_cache_size = 4096

[dir]
# Size of LRU cache of contents of directories.
lru_cache_size = 4096
# Cache timeout for content of directories.
# If content is expired but still in LRU cache, it will check whether the content is changed
# using cTag and may refresh the cache.
cache_ttl = 30
